### ISSUE TITLE
Examples are out of data

### ISSUE THREAD

**Issue by lukedempsey** [lbl-srg/EstimationPy#2]
The examples have fallen behind the source code. 
Mainly module and method names need to be updated so that they are linked again.

I'm aware that this repo looks pretty stale, just raising this so that someone doesn't think the whole repo is broken just because their examples won't compile.

**Comment by lukedempsey** [comment]
There are actually a fair few things that I've run into that seem broken/out of date:

I attempted to fix them on my fork, but ended up giving up on this repo due to all of the hurdles.
https://github.com/lukedempsey/EstimationPy

Note that the fixes were done to get the damn thing running, so I didn't really pay much attention to side-effects

It simulates, but parameter estimation (what I wanted to use) doesn't work

**Comment by dhblum** [comment]
I raised a number of specific issues in #4, #5, #6, #7, #8, and #9.  A number of fixes were made in #3 and #10.  Remaining issues are reported in #6 and #8.

I will close this issue in favor of the remaining open issues that provide more detail, and any further that are reported.
